### PR TITLE
feat: use dynamic import to import codemods

### PR DESCRIPTION
**Pull request by ronanru**
When multiple people are commiting codemods at the same time, they get a merge conflict in `codemods/index.js`. We can avoid this, if we use dynamic imports to construct the codemods object

### CODE REVIEW

**Comment by thepassle** [comment]
LGTM, I do think its nice to have a sync object available that we can index with package names that doesn't depend on an async function, maybe in the future we can do something like:

```js
const codemods = {
  'foo-bar': () => import('./codemods/foo-bar/index.js')
}
```

but I agree, we're getting a lot more PRs now and the conflicts are becoming a bit of an issue, so for now lets go with this

Can you fix the conflict (😅) and then merge?

**Review by thepassle — APPROVED** [review]

**Comment by MeLlamoPablo** [comment]
@ronanru tests don't seem to be running after this PR. See how [in this run](https://github.com/thepassle/module-replacements-codemods/actions/runs/10029189924/job/27717062172) the runner says "pass: 1". Only the first codemod seems to be detected.

Screenshot 2024-07-21 at 18 03 40

**Comment by thepassle** [comment]
@ronanru I think this PR also broke the `which` script 😄

**Comment by ronanru** [comment]
Sorry

**Comment by thepassle** [comment]
All good :) thanks for the fix!

**Pull request merged**
