### PR TITLE
Replace md5 package

### PR DESCRIPTION
**Pull request by filipre**
Hi!

This PR replaces [md5](https://www.npmjs.com/package/md5) with the build-in `crypto` package. I'm using codemods and `jscodeshift` for the first time so I'd appreciate some feedback on the PR:
- It replaces `import md5 from 'md5'` successfully. What about `var md5 = require('md5');`? Do I need to handle this? Should this live in the same transformation file?
- What does `dirtyFlag` do?
- Should I transform to single or double quotes?
- Should I worry that this only works for node and not front end projects?

The replacement is based on [this](https://stackoverflow.com/questions/1655769/fastest-md5-implementation-in-javascript) SO answer. I also tested the generated code locally and it looks fine to me:
```bash
# test a string
~/Development/node-playground> node md5-package.js
78e731027d8fd50ed642340b7c9a63b3
~/Development/node-playground> node md5-crypto.js
78e731027d8fd50ed642340b7c9a63b3

# test a buffer
~/Development/node-playground> node md5-buffer-package.js
cf778431631ef17d1e8bb1b84e13d25a
~/Development/node-playground> node md5-buffer-crypto.js
cf778431631ef17d1e8bb1b84e13d25a
```

### CODE REVIEW

**Comment by ronanru** [comment]
Please run "npm format" to format the code

**Comment by thepassle** [comment]
Thanks for the PR! Nice to hear that this is the first codemod you created 🙂

> It replaces import md5 from 'md5' successfully. What about var md5 = require('md5');? Do I need to handle this? Should this live in the same transformation file?

We have a function here: https://github.com/thepassle/module-replacements-codemods/issues/new?permalink=https%3A%2F%2Fgithub.com%2Fthepassle%2Fmodule-replacements-codemods%2Fblob%2Fd2a6c2f34546e493227d304682dcdf9299a3ae84%2Fcodemods%2Fshared.js%23L13

That will get the imported identifier from `'md5'` (for both esm/cjs), which you can then use to find usages of that identifier. You can find some example usage of this function in the other codemods, but it would look something like:

```js
const { identifier } = removeImport(
  'md5',
  root,
  j,
);
root.find(j.ImportDeclaration, { source: { value: 'md5' } }) // etc
```

> What does dirtyFlag do?

The `dirtyFlag` is kind of underutilized right now, since the `transform` function should return a string anyways. I'll likely refactor this at a later point in time for all the codemods, so no need to worry about it for now.

> Should I transform to single or double quotes?

Single quotes

> Should I worry that this only works for node and not front end projects?

I think that's fine for now, my main concern for now is gathering as many codemods as possible. Once we have a substantial body of codemods, we can do some testing on real world projects and make improvements.

Thanks again for the PR, this is great work! As a final note, like @ronanru mentioned, could you run `npm run format` and push the changes?

**Comment by filipre** [comment]
This makes a few things clearer, thanks! Maybe you can help me out with a few things here. I also added more test cases, which are currently failing though.
- Take a look at the result in `case-1`. Why does line 1 have a `;`  but line 2 does not? In general, should the output have it or not?
- I don't think I can use `removeImport` because I have to replace the module with a new one and the function there removes the reference. I couldn't find a codemod that *replaces* the module name. If this is new, should we introduce a new function in `shared.js`?
- Also I am not sure how to handle `case-4` (`a.md5 = require('md5')`) or even more complicated code like `a.b.c.d.md5 = require('md5');`. Do you know the best way?

**Comment by thepassle** [comment]
> Take a look at the result in case-1. Why does line 1 have a ; but line 2 does not? In general, should the output have it or not?

I think because the `before` doesnt have a semicolon there either

> I don't think I can use removeImport because I have to replace the module with a new one and the function there removes the reference. I couldn't find a codemod that replaces the module name. If this is new, should we introduce a new function in shared.js?

Ah yes indeed. Yeah we can make a `replaceImport` function or something like that, we should be able to reuse most of logic from `removeImport`

> Also  I am not sure how to handle case-4 (a.md5 = require('md5')) or even more complicated code like a.b.c.d.md5 = require('md5');. Do you know the best way?

We can worry about these more advanced usecases later :)

**Comment by filipre** [comment]
>We can worry about these more advanced usecases later :)

Alright, I couldn't figure it out so let's leave it for another time. I introduced the function `replaceDefaultImport`. What do you think?

**Comment by thepassle** [comment]
I think it looks good to me! Nice work, thanks for sticking with the PR!

**Pull request merged**
